# Railway Nixpacks configuration

[phases.setup]
nixPkgs = ['nodejs', 'nodePackages.pnpm', 'nodePackages.ts-node']

[phases.install]
cmd = ["pnpm install -r", "cd packages/server && pnpm i", "cd packages/client && pnpm i"]

[phases.build]
cmd = "cd packages/client && pnpm build"

[start]
cmd = "cd packages/server && pnpm start"

[variables]
NODE_ENV = "production"
PROXY_WEBSOCKET=true