# Railway Nixpacks configuration

[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ["npm i -g pnpm", "pnpm install -r"]

[phases.build]
cmd = "pnpm build"

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"