# Railway Nixpacks configuration

[phases.setup]
nixPkgs = ['nodejs', 'nodePackages.pnpm']

[phases.install]
cmd = "pnpm install"

[phases.build]
cmd = "pnpm build"

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"